sudo: false
language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
    - TOXENV=django18
    - TOXENV=django19
    - TOXENV=django110
    - TOXENV=django111
    - TOXENV=django20
matrix:
    exclude:
    - python: 3.6
      env: TOXENV=django18
    - python: 3.6
      env: TOXENV=django19
    - python: 3.6
      env: TOXENV=django110
    - python: 3.5
      env: TOXENV=django18
    - python: 3.4
      env: TOXENV=django19
    - python: 3.4
      env: TOXENV=django110
    - python: 3.4
      env: TOXENV=django111
    - python: 2.7
      env: TOXENV=django20
    - python: 3.4
      env: TOXENV=django20
    - python: 3.5
      env: TOXENV=django20

before_install:
    - pip install tox

script: tox

notifications:
  email: false
  irc: false
